#NUMPY of Python: Numerical python

#Why NP

*   ndarray, an efficient multidimensional array providing fast array-oriented arithmetic
operations 

*  Flexible broadcasting capabilities.
*  Mathematical functions for fast operations on entire arrays of data without having
to write loops. 

*    Tools for reading/writing array data to disk and working with memory-mapped files
*   Linear algebra, random number generation, and Fourier transform capabilities.


*    A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.List item


*   stores array data in contiguous memory for faster access thereby providing efficiency compared to other sequence objects in Python





In [252]:
import numpy as np


In [3]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [4]:
type(my_arr)

numpy.ndarray

#wall-clock time:  measures the total time to execute a program in a computer 

In [5]:
%time for _ in range(10): my_arr2 = my_arr * 2


Wall time: 16.5 ms


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 520 ms


##np.random.rand function: 

*   creates Numpy arrays (row-major) of specified shape that contain random values between 0 and 1.
*   the probability of selecting specific numbers between 0 and 1 is uniform.

 

In [253]:
data = np.random.rand(3, 3) 
print(data)

[[0.10833736 0.96259288 0.11552301]
 [0.46088262 0.83163784 0.04587908]
 [0.7820273  0.28706619 0.65503345]]


#exploring characteristics of data

In [254]:
type(data)

numpy.ndarray

In [255]:
data.dtype

dtype('float64')

In [256]:
print("size:total elements:{0}  order:{1}   numberof dimensions: {2}".format(data.size, data.shape, data.ndim))

size:total elements:9  order:(3, 3)   numberof dimensions: 2


#random data from normal distribution

In [257]:
data = np.random.randn(3, 3) 
print(data)

[[ 2.06927526 -0.45555111 -0.98540962]
 [ 0.22590212  0.06394588  0.98560278]
 [-0.14737751 -0.24144389 -0.14594612]]


 # copying content of an array using = operator makes a new copy i.e. changes done on new object is not reflected in the source
Broadcasting: applying specified operation on each element of the array
However both operands of an operator may not be same in size

In [14]:
A1=data*2
A1

array([[0.01095118, 0.44230172, 1.40803006],
       [1.12614371, 1.95416506, 1.41449775],
       [1.70637957, 1.91484325, 0.2828172 ]])

 #Broadcasting is used to apply arithmetic on arrays of unequal size
-the smaller array is “broadcast” across 

*   the smaller array is “broadcast” across the larger array so that they have compatible shapes
*  provides a means of vectorizing array operations so that looping occurs in C instead of Python
*rank of the array are compared to apply broadcasting where rank indicates number of dimensions of the array

#simple way to do same computation on all the elements of an array
1. Any arithmetic operations between equal-size arrays applies the operation elementwise
2. if one operand is array and other scalar, then scalar value is propagated

In [ ]:
A1=A1+5
A1

array([[6.63157891, 6.22670558, 5.12804498],
       [5.18882094, 5.8181272 , 6.12407304]])

In [258]:
data

array([[ 2.06927526, -0.45555111, -0.98540962],
       [ 0.22590212,  0.06394588,  0.98560278],
       [-0.14737751, -0.24144389, -0.14594612]])

In [259]:
5+2*data

array([[9.13855052, 4.08889778, 3.02918076],
       [5.45180424, 5.12789177, 6.97120557],
       [4.70524498, 4.51711222, 4.70810775]])

## generate numbers from the specified range arange() and store in 1d array

In [260]:
A2=np.arange(1,32,2)
print(A2.size, A2.shape)
A2

16 (16,)


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

# converting 1D array to 2D array using  
reshape(a, newshape, order='C')

order= {'C', 'F', 'A'} and is optional

*   C: By default orde is C-like  array i.e row-wise

*   F: column wise conversion of 1D numpy array to 2D Numpy array as in Fortran

*  A: Fortran like indexing for in-contiguous memory else C-like


*   **reshape() returns a view of the original array**
*   size of input array should be equivalent to size of new array


In [265]:
A3=np.reshape(A2, (2,8), order='C')

In [269]:
A2

array([100,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31])

In [267]:
A3[0,0]=100

In [270]:
A3=np.reshape(A2, (2,8), order='F')
A3

array([[100,   5,   9,  13,  17,  21,  25,  29],
       [  3,   7,  11,  15,  19,  23,  27,  31]])

In [273]:
A3.base is A2

True

In [68]:
A2.base is None

True

# More on shape:
-1 in shape (4,-1) indicates setting of second  dimension shape as per the original array size considering size of first dimension (16) and rest of dimensions specified (here 4). Only one dimension shape can be -1

In [274]:
A2.ndim

1

In [278]:
A3=np.reshape(A2, (4,-1), order='C')
A3

array([[100,   3,   5,   7],
       [  9,  11,  13,  15],
       [ 17,  19,  21,  23],
       [ 25,  27,  29,  31]])

## reshape..(1,-1) results into 2d array only

In [71]:
A3

array([[100,   3,   5,   7],
       [  9,  11,  13,  15],
       [ 17,  19,  21,  23],
       [ 25,  27,  29,  31]])

In [279]:
A5=np.reshape(A3, (1,-1), order='C')
A5.ndim

2

## original array address is used OR NOT
### ndarray has an attribute called base to check  base of an array that owns its memory. It  is None for A2 (as it is the original array) . But for A3, A5 base is A2  because they are is just views of A5.

In [96]:
A3.base is A2

True

## to know whether two array share same memory location

In [284]:
A1

array([0.53536634, 0.37683539, 0.50273395, 0.35167743, 0.43676739,
       0.22446534, 0.00444202, 0.31848072, 0.77239245, 0.62014837])

In [283]:
print (np.may_share_memory(A5, A1))

False


In [286]:
A5

array([[100,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
         27,  29,  31]])

In [285]:
A5.shape

(1, 16)

In [287]:
A5[0,4]=300

In [288]:
A5

array([[100,   3,   5,   7, 300,  11,  13,  15,  17,  19,  21,  23,  25,
         27,  29,  31]])

## to flatten 2d array into 1d array

In [289]:
A6=A5.flatten()

In [290]:
A6.ndim

1

In [291]:
A6

array([100,   3,   5,   7, 300,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31])

In [292]:
A6.base is None

True

In [293]:
print (np.may_share_memory(A5, A6))

False


In [294]:
A6[2]=200

In [295]:
A5

array([[100,   3,   5,   7, 300,  11,  13,  15,  17,  19,  21,  23,  25,
         27,  29,  31]])

## difference in reshape() and flatten()
1. reshape() creates a view wheras flatten make a copy
2. reshape() used for increasing dimensions where flatten is used for converting to 1d array of contiguous location
3. in both cases size is same in original and new arrays

## difference in ravel and flatten()
flatten makes a copy but ravel makes a view
while using ravel we may mention order of arranging elements as done in reshape()

In [298]:
A5

array([[100,   3,   5,   7, 555,  11,  13,  15,  17,  19,  21,  23,  25,
         27,  29,  31]])

In [296]:
A7=A5.ravel()

In [297]:
A7[4]=555

In [97]:
A5

array([[100,   3,   5,   7, 300,  11,  13,  15,  17,  19,  21,  23,  25,
         27,  29,  31]])

In [299]:
A3.shape

(4, 4)

In [300]:
A8=A3.reshape(-1)

In [302]:
A8.base is A2

True

## creating array from underlying list with numeric data

In [303]:
l=[1,2,3,4,5]
l1=[[1,2,3],[4,5,6]]
a1=np.array(l)
a2=np.array(l1)
print(a1.shape,a2.shape)
print(a1.ndim, a2.ndim)
print(a1)

(5,) (2, 3)
1 2
[1 2 3 4 5]


In [308]:
a2

array([[ 1,  2, 10],
       [ 4,  5, 10]])

In [312]:
a2[0:,0:2]*6

array([[ 6, 12],
       [24, 30]])

In [315]:
a1

array([1, 2, 3, 4, 5])

## vectorization : applying same operation on two equal sized arrays without looping
## vectorization of a function means that the function is now applied simultaneously over many values instead of a single value
Done thru underlying C-code

In [319]:
a1>a2  #not feasible

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [316]:
a2=a2.flatten()

In [317]:
a2.shape

(6,)

In [318]:
a1.shape

(5,)

In [126]:
a2.shape

(6,)

In [320]:
if a1.size==a2.size:
  pass
elif a1.size>a2.size:
  a3=a1[:a2.size]
  a4=a2
else:
  a3=a2[:a1.size]
  a4=a1


In [321]:
print(a3,a4)

[ 1  2 10  4  5] [1 2 3 4 5]


In [322]:
a3 >= a4

array([ True,  True,  True,  True,  True])

## array may have non-numeric data as in list

In [324]:
l=['1','2','3','4','5']
a1=np.array(l)
a1

array(['1', '2', '3', '4', '5'], dtype='<U1')

## incase list is not symmeteric  nested list (ragged sequence), warning is shown. shape is only taken as (1,) i.e  second dimension is incomplete

In [325]:
l1=['1','2',['3','4'],'5']
a1=np.array(l1)
a1

C:\Users\SHARAN~1\AppData\Local\Temp/ipykernel_20108/1362869433.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a1=np.array(l1)


array(['1', '2', list(['3', '4']), '5'], dtype=object)

In [327]:
a1.ndim

1

In [329]:
type(a1[2])

list

In [330]:
type(l1[2])

list

In [130]:
a1.shape

(4,)

In [331]:
a1.dtype

dtype('O')

In [132]:
x=a1.dtype
x.name

'object'

## creating arrays of 0/1

In [332]:
n1=np.zeros(5)
n2=np.ones(5)


In [333]:
print(n1,'\n',n2)

[0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1.]


## you may mention type of elements

In [334]:
n3=np.zeros((2,3),int)
n3

array([[0, 0, 0],
       [0, 0, 0]])

In [335]:
n2.dtype

dtype('float64')

## grabage value in array when using empty()

In [341]:
n4=np.empty((2,3,3)) 

In [343]:
n4[:,:]=0

In [344]:
n4

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## takes another array and creates new array of same shape and size but having ones only

In [345]:
n3

array([[0, 0, 0],
       [0, 0, 0]])

In [142]:
n5=np.ones_like(n3)
n5

array([[1, 1, 1],
       [1, 1, 1]])

## full() to populate same element as specified by the user

In [346]:
n1=np.full((2,3),7)
n1

array([[7, 7, 7],
       [7, 7, 7]])

In [347]:
n1[1][2]=10
n1

array([[ 7,  7,  7],
       [ 7,  7, 10]])

## identity matrix (diagonal one)

In [348]:
m2=np.identity(4)
print(m2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## eye() to have all zeros except for the  k^{th}  which is mentioned

In [350]:
m1=np.eye(4,4,-1)
m1

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## -2 in eye() means below the major column

In [154]:
m1=np.eye(4,4,-2)
m1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [351]:
s1=np.array(['aa','xxx','sdf','sd']).reshape((2,2))
s1

array([['aa', 'xxx'],
       ['sdf', 'sd']], dtype='<U3')

In [352]:
s1.dtype

dtype('<U3')

### dtype('<U3') is a little-endian 3 character string.

In [354]:
arr1 = np.array([1, 2, 3, 4, 5],str)
arr1.dtype


dtype('<U1')

different data types

https://drive.google.com/file/d/1QLzvEeBvi8n8RQwQlXh4FBsipc_TyyKf/view?usp=sharing

#astype(): to assign values of source array as per new specified data type

In [355]:
arr2 = arr1.astype(np.float64)
arr2.dtype

dtype('float64')

In [356]:
arr2

array([1., 2., 3., 4., 5.])

In [165]:
arr1 = arr1.astype(np.int32)
arr1.dtype

dtype('int32')

In [357]:
arr2=arr2*2
print(arr1,arr2)

['1' '2' '3' '4' '5'] [ 2.  4.  6.  8. 10.]


In [167]:
arr1+arr2

array([ 3.,  6.,  9., 12., 15.])

In [ ]:
numeric_strings = np.array(['1.25', '-9.6', '42'])
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

## what is happening here?

In [358]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
I=int_array.astype(calibers.dtype)
print(int_array[0].dtype,I.dtype)

int32 float64


## Basic indexing and broadcasting
Why loops are slow in Python:
goes line-by-line through the code, 

1.   execution line by line, compiles code into bytecode
2.   Python is dynamically type i.e it has no idea what type of objects are present in the list 
3. Need to do : determining the type of variable, resolving it's scope, checking for any invalid operations etc. in each iteration which is time-consuming



## How is array handled in Numpy?
NumPy allows arrays to only have a single data type and stores the data internally in a contiguous block of memory, which allows optimization of code, pre-compiled C code under the hood.

In [171]:
L=[1,2,3,4]
L[:2]

[1, 2]

In [359]:
I

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## ##array created using slicing is a view of original array just like list

In [172]:
I[1:5]

array([1., 2., 3., 4.])

In [360]:
I[:2]=20
I

array([20., 20.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [361]:
A1=I[:2]
A1[0]=100

In [362]:
I

array([100.,  20.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.])

## to create an independent copy using slicing use copy()

In [176]:
A3=I[:2].copy()
print(A3,I)

[100.  20.] [100.  20.   2.   3.   4.   5.   6.   7.   8.   9.]


In [ ]:
A3[0]=10000
print(A3,I)

[10000.    20.] [100.  20.   2.   3.   4.   5.   6.   7.   8.   9.]


#accessing elements in higher dimensions

In [363]:
A1=np.arange(1,32,2,int)
A2=A1.reshape((2,8))
A2

array([[ 1,  3,  5,  7,  9, 11, 13, 15],
       [17, 19, 21, 23, 25, 27, 29, 31]])

In [178]:
A1.size

16

#link for 2D
https://drive.google.com/file/d/1rThKxSDPMExZc06ElY3XNYwldBDjS-qA/view?usp=sharing

In [ ]:
A2

array([[ 1,  3,  5,  7,  9, 11, 13, 15],
       [17, 19, 21, 23, 25, 27, 29, 31]])

In [179]:
A2[0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [365]:
A2[0,5:]

array([11, 13, 15])

In [181]:
A2[1][2]

21

##another alternatives is to use comma seperator

In [182]:
A2[0,2]

5

In [183]:
A2[1,7]

31

#3 Dimensional array

In [366]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [367]:
arr3d.ndim

3

In [368]:
arr3d.shape

(2, 2, 3)

In [369]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [370]:
c=arr3d[0]
c.ndim

2

In [371]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [372]:
c[0,1]=100
c

array([[  1, 100,   3],
       [  4,   5,   6]])

In [373]:
arr3d

array([[[  1, 100,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [374]:
arr3d[0,1]

array([4, 5, 6])

In [375]:
arr3d[0][1]

array([4, 5, 6])

In [193]:
arr3d

array([[[  1, 100,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [194]:
arr3d[:1,:2]

array([[[  1, 100,   3],
        [  4,   5,   6]]])

only : operator indicates entire axis

In [195]:
arr3d[:,:1]

array([[[  1, 100,   3]],

       [[  7,   8,   9]]])

## Boolean indexing: access axis value on the basis of T/F
Given is an array of names of students along with marks in three subjects for each student in array data

In [377]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.arange(10, 115,5) #100*randn
data=data.reshape((7,3))
names
data.size

21

In [378]:
data

array([[ 10,  15,  20],
       [ 25,  30,  35],
       [ 40,  45,  50],
       [ 55,  60,  65],
       [ 70,  75,  80],
       [ 85,  90,  95],
       [100, 105, 110]])

In [379]:
names=='Joe'

array([False,  True, False, False, False,  True,  True])

In [380]:
data

array([[ 10,  15,  20],
       [ 25,  30,  35],
       [ 40,  45,  50],
       [ 55,  60,  65],
       [ 70,  75,  80],
       [ 85,  90,  95],
       [100, 105, 110]])

#Boolean array must be same in length as that of axis size


1.  Note that  logical keywords and/or/not cannot be directly used in boolean array instead use (&/|/!) signs 
2.   selecting data using boolean indexing always create a new copy. No change in source array



In [381]:
data[names=='Joe']

array([[ 25,  30,  35],
       [ 85,  90,  95],
       [100, 105, 110]])

In [382]:
data[names == 'Joe', 2]

array([ 35,  95, 110])

In [383]:
data[~(names=='Joe')]

array([[10, 15, 20],
       [40, 45, 50],
       [55, 60, 65],
       [70, 75, 80]])

## select those rows from data which corresponds to either 'Bob' or 'Joe'. 

In [205]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [384]:
condition=  (names=='Joe')|(names=='Bob')
condition

array([ True,  True, False,  True, False,  True,  True])

In [385]:
data[condition]

array([[ 10,  15,  20],
       [ 25,  30,  35],
       [ 55,  60,  65],
       [ 85,  90,  95],
       [100, 105, 110]])

## select data for students who are not Bob or Joe

In [ ]:
names[~condition]

array(['Will', 'Will'], dtype='<U4')

In [208]:
data[~condition]

array([[40, 45, 50],
       [70, 75, 80]])

## to set marks for 'will' to 0

In [ ]:
print(data,'\n',names)

[[ 10  15  20]
 [ 25  30  35]
 [ 40  45  50]
 [ 55  60  65]
 [ 70  75  80]
 [ 85  90  95]
 [100 105 110]] 
 ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


In [387]:
data[names=='Will']=0
data

array([[ 10,  15,  20],
       [ 25,  30,  35],
       [  0,   0,   0],
       [ 55,  60,  65],
       [  0,   0,   0],
       [ 85,  90,  95],
       [100, 105, 110]])

In [211]:
data

array([[ 10,  15,  20],
       [ 25,  30,  35],
       [  0,   0,   0],
       [ 55,  60,  65],
       [  0,   0,   0],
       [ 85,  90,  95],
       [100, 105, 110]])

In [212]:
data[data>100]=100
data

array([[ 10,  15,  20],
       [ 25,  30,  35],
       [  0,   0,   0],
       [ 55,  60,  65],
       [  0,   0,   0],
       [ 85,  90,  95],
       [100, 100, 100]])

## Fancy indexing: indexing using integer array

In [213]:
data


array([[ 10,  15,  20],
       [ 25,  30,  35],
       [  0,   0,   0],
       [ 55,  60,  65],
       [  0,   0,   0],
       [ 85,  90,  95],
       [100, 100, 100]])

## get specified row indexes in an array, -ve index value starts accessing row from the last row as in list,
to access rows in any order

In [214]:
data[[1,0,3]]

array([[25, 30, 35],
       [10, 15, 20],
       [55, 60, 65]])

In [215]:
data[[-2,-6]]

array([[85, 90, 95],
       [25, 30, 35]])

## to access particular elements using tuples of indices
[x,y,z],[a,b,c]=>[x,a][y,b][z,c]
Result of fancy index is always one dimensional array

In [216]:
data[[1,2,4],[0,1,2]]

array([25,  0,  0])

#retrieving subset of the specified rows

In [217]:
data[[1,2,5]]

array([[25, 30, 35],
       [ 0,  0,  0],
       [85, 90, 95]])

In [101]:
data[[1,2,5]][:,[0,2]]

array([[25, 35],
       [40, 50],
       [85, 95]])

In [218]:
data[[1,2,5]][1:,[0,2]]

array([[ 0,  0],
       [85, 95]])

## transpose of a matrix

In [219]:
data.shape

(7, 3)

In [220]:
d1=data.T

In [221]:
data.shape

(7, 3)

In [222]:
d1.shape

(3, 7)

## shapes need to be aligned while using dot product=> matrix multuplication

In [223]:
np.dot(data,data.T)

array([[  725,  1400,     0,  2750,     0,  4100,  4500],
       [ 1400,  2750,     0,  5450,     0,  8150,  9000],
       [    0,     0,     0,     0,     0,     0,     0],
       [ 2750,  5450,     0, 10850,     0, 16250, 18000],
       [    0,     0,     0,     0,     0,     0,     0],
       [ 4100,  8150,     0, 16250,     0, 24350, 27000],
       [ 4500,  9000,     0, 18000,     0, 27000, 30000]])

In [388]:
data1=np.ones((3,2))
data2=np.ones((2,3))

In [389]:
data1.dot(data2)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [390]:
data1*data2

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [234]:
data.shape

(7, 3)

In [391]:
data1[:2,0:2]*data2[:,0:2]

array([[1., 1.],
       [1., 1.]])

## swapaxes: to swap two axes or dimesnions i.e. rows to columns and v.v.

In [233]:
data.swapaxes(1,0).shape

(3, 7)

## generating a 3D array

reshaping using object method

#another alternative as passing array object as argument and get reshaped

In [ ]:
L=np.random.randn(15)
L1=np.reshape(L,(3,5))
L1

In [114]:
L=np.arange(0,24)
L1=L.reshape((4,6))
print(L.shape,L1.shape)

(24,) (4, 6)


In [115]:
print(L1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


## in 3D, transpose takes axis numbers to be reordered where axis
0: matrix
1:row
2:column

In [116]:
arr1=np.arange(0,24).reshape((2,4,3))

In [117]:
arr1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [ ]:
print(arr1.ndim,arr1.shape)

3 (2, 4, 3)


In [118]:
arr1.transpose((0,1,2))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [ ]:
arr1.transpose((2,1,0))

#make new 3D list  using row,col,matrix

In [121]:
arr1.transpose((1,2,0))

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14]],

       [[ 3, 15],
        [ 4, 16],
        [ 5, 17]],

       [[ 6, 18],
        [ 7, 19],
        [ 8, 20]],

       [[ 9, 21],
        [10, 22],
        [11, 23]]])

In [122]:
arr1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

#need to transpose each matrix in the given 3D array

In [119]:
arr1.transpose((0,2,1))

array([[[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]],

       [[12, 15, 18, 21],
        [13, 16, 19, 22],
        [14, 17, 20, 23]]])

#alternative use swapaxes()

In [ ]:
arr1.swapaxes(2,1)

array([[[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]],

       [[12, 15, 18, 21],
        [13, 16, 19, 22],
        [14, 17, 20, 23]]])

In [ ]:
arr1.swapaxes(0,1)

array([[[ 0,  1,  2],
        [12, 13, 14]],

       [[ 3,  4,  5],
        [15, 16, 17]],

       [[ 6,  7,  8],
        [18, 19, 20]],

       [[ 9, 10, 11],
        [21, 22, 23]]])

#statistical  methods sum() mean() cumsum() cumprod()

In [123]:
data

array([[ 10,  15,  20],
       [ 25,  30,  35],
       [ 40,  45,  50],
       [ 55,  60,  65],
       [ 70,  75,  80],
       [ 85,  90,  95],
       [100, 105, 110]])

In [ ]:
data.shape

(7, 3)

In [392]:
data.sum()

900

In [394]:
data

array([[ 10,  15,  20],
       [ 25,  30,  35],
       [  0,   0,   0],
       [ 55,  60,  65],
       [  0,   0,   0],
       [ 85,  90,  95],
       [100, 105, 110]])

#sum along columns resulted in an array of one less dimension

In [395]:
data.sum(axis=0)

array([275, 300, 325])

In [126]:
data.sum(axis=0)

array([385, 420, 455])

In [ ]:
arr1.sum()

276

In [127]:
data[2:4]=0
data

array([[ 10,  15,  20],
       [ 25,  30,  35],
       [  0,   0,   0],
       [  0,   0,   0],
       [ 70,  75,  80],
       [ 85,  90,  95],
       [100, 105, 110]])

In [ ]:
arr1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

#accessing a matrix using fancy index

In [139]:
arr1[[1]].shape

(1, 4, 3)

In [138]:
arr1[[1]][:,2:,1]

array([[19, 22]])

In [141]:
arr1.sum(axis=1)

array([[18, 22, 26],
       [66, 70, 74]])

In [142]:
L1=np.random.rand(5)
L1

array([0.80276013, 0.12935599, 0.86526157, 0.20223303, 0.4075163 ])

In [143]:
L1.sort()
L1

array([0.12935599, 0.20223303, 0.4075163 , 0.80276013, 0.86526157])

#
Let  us revise

In [144]:
a=np.random.randint(1,120,16)
a

array([ 91,  88, 118,  46,  30, 110,  19,  58,  16,  26, 110,  47,  60,
         9,  83,  62])

In [145]:
a.shape=(4,4)

In [146]:
a

array([[ 91,  88, 118,  46],
       [ 30, 110,  19,  58],
       [ 16,  26, 110,  47],
       [ 60,   9,  83,  62]])

In [ ]:
a[-2]

In [148]:
a[1:,-3:-1]

array([[110,  19],
       [ 26, 110],
       [  9,  83]])

In [149]:
a[[1,2]]=100

In [152]:
a

array([[ 91,  88, 118,  46],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [ 60,   9,  83,  62]])

In [153]:
a1=np.arange(1,5,1)
a1

array([1, 2, 3, 4])

#broadcasting on a matrix, one of the index should match
    + and * is commutative and elementwise
    - and / is not commutative but elementwise

In [154]:
a+a1

array([[ 92,  90, 121,  50],
       [101, 102, 103, 104],
       [101, 102, 103, 104],
       [ 61,  11,  86,  66]])

In [45]:
a

array([[ 49,  50,  15,  50],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [ 27,  90,  81,  89]])

In [155]:
a=np.ones((3,4))

In [156]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
a1

array([1, 2, 3, 4])

In [157]:
a*a1

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [158]:
a1*a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [159]:
a1-a

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [160]:
a-a1

array([[ 0., -1., -2., -3.],
       [ 0., -1., -2., -3.],
       [ 0., -1., -2., -3.]])

In [163]:
a=np.ones((3,1))
a1=np.arange(1,5)

In [164]:
print(a.shape,a1.shape)

(3, 1) (4,)


In [166]:
print(a,'\n',a1)

[[1.]
 [1.]
 [1.]] 
 [1 2 3 4]


In [165]:
a+a1

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [57]:
a1*a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
a=np.ones((3,4))
a1=np.arange(1,13).reshape(3,4)

In [ ]:
a+a1

array([[ 2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9.],
       [10., 11., 12., 13.]])

In [167]:
a=np.ones((3,5))
a1=np.arange(1,4).reshape((3,1))

In [169]:
a1.shape

(3, 1)

In [168]:
print(a,"\n",a1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 
 [[1]
 [2]
 [3]]


In [170]:
a+a1

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

#find the output?

In [171]:
a=np.zeros((3,5))
a.shape[0]

3

In [174]:
for i in range(a.shape[0]):
  a[i]=i*3

In [62]:
a

array([[0., 0., 0., 0., 0.],
       [3., 3., 3., 3., 3.],
       [6., 6., 6., 6., 6.]])

## another example for extracting elements of an array: guess what is happening here?

In [236]:
a=np.random.randint(1,50,12)
a.shape=(3,4)

In [237]:
a

array([[12, 47, 33, 46],
       [27, 23, 25, 47],
       [22, 38, 48, 39]])

In [238]:
L=a%2!=0
L

array([[False,  True,  True, False],
       [ True,  True,  True,  True],
       [False, False, False,  True]])

In [239]:
print(a[L])

[47 33 27 23 25 47 39]


In [240]:
L=a%2
L


array([[0, 1, 1, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 1]], dtype=int32)

In [242]:
L[0]

array([0, 1, 1, 0], dtype=int32)

In [243]:
L[1]

array([1, 1, 1, 1], dtype=int32)

In [241]:
a[L[0],L[1]]

array([47, 23, 23, 47])

#each row in the array passed as index is used as fancy index for accessing element of main array

In [181]:
a[L]

array([[[ 5, 27, 22, 41],
        [39, 24, 13, 31],
        [ 5, 27, 22, 41],
        [ 5, 27, 22, 41]],

       [[ 5, 27, 22, 41],
        [ 5, 27, 22, 41],
        [39, 24, 13, 31],
        [ 5, 27, 22, 41]],

       [[39, 24, 13, 31],
        [ 5, 27, 22, 41],
        [ 5, 27, 22, 41],
        [39, 24, 13, 31]]])

In [235]:
l=np.random.randint(0,3,12)
l

array([0, 2, 2, 2, 2, 2, 0, 1, 0, 0, 2, 2])

In [185]:
a

array([[39, 24, 13, 31],
       [ 5, 27, 22, 41],
       [46, 49, 37,  6]])

In [184]:
l=l.reshape(3,4)
l

array([[0, 0, 1, 1],
       [1, 1, 2, 0],
       [0, 1, 1, 1]])

In [186]:
a[l]

array([[[39, 24, 13, 31],
        [39, 24, 13, 31],
        [ 5, 27, 22, 41],
        [ 5, 27, 22, 41]],

       [[ 5, 27, 22, 41],
        [ 5, 27, 22, 41],
        [46, 49, 37,  6],
        [39, 24, 13, 31]],

       [[39, 24, 13, 31],
        [ 5, 27, 22, 41],
        [ 5, 27, 22, 41],
        [ 5, 27, 22, 41]]])

In [248]:
A2=np.random.randn(10)

In [249]:
A1=np.random.rand(10)

In [251]:
np.maximum(A1,A2)

array([1.80128155, 0.37683539, 1.20060389, 0.35167743, 1.89230309,
       0.22446534, 0.00444202, 0.68251149, 1.4841006 , 1.06770708])

In [245]:
np.sqrt(A1)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894,
       4.58257569, 4.79583152, 5.        , 5.19615242, 5.38516481,
       5.56776436])