# data cleaning part-II

In [1]:
import pandas as pd 
import numpy as np

# to upload files in content folder in colab
from google.colab import files
uploaded = files.upload()

In [2]:
DF=pd.read_csv('weather.csv',na_values=np.nan)
DF

Season   Weather  Tourist Labels
0  Summer  Pleasant     like    Yes
1  Summer       Hot  dislike    Yes
2  Summer  Pleasant     like    Yes
3  winter     Harsh     like    Yes
4  winter  Pleasant     like     No
5  autumn       Dry  dislike    Yes
6  autumn  Pleasant  dislike    Yes
7  autumn     Harsh      NaN     No
8  Spring  Pleasant     like    NaN

In [5]:
DF['cost']=DF['Season'].map(lambda x: 100 if x =='Summer' else (150 if x=='winter' else 200 ))

In [110]:
DF

Season   Weather  Tourist Labels  cost
0  Summer  Pleasant     like    Yes   100
1  Summer       Hot  dislike    Yes   100
2  Summer  Pleasant     like    Yes   100
3  winter     Harsh     like    Yes   150
4  winter  Pleasant     like     No   150
5  autumn       Dry  dislike    Yes   200
6  autumn  Pleasant  dislike    Yes   200
7  autumn     Harsh      NaN     No   200
8  Spring  Pleasant     like    NaN   200

In [152]:
DF['extra']=np.random.randn(len(DF))
DF

Season   Weather  Tourist Labels  cost     extra
0  Summer  Pleasant     like    Yes   100 -0.370092
1  Summer       Hot  dislike    Yes   100 -1.311576
2  Summer  Pleasant     like    Yes   100  0.435747
3  winter     Harsh     like    Yes   150  0.710793
4  winter  Pleasant     like     No   150 -0.337188
5  autumn       Dry  dislike    Yes   200 -1.328733
6  autumn  Pleasant  dislike    Yes   200  0.740227
7  autumn     Harsh      NaN     No   200  1.379750
8  Spring  Pleasant     like    NaN   200 -0.209773

In [15]:
DF['extra']=np.random.randint(1,130,len(DF))

In [252]:
DF

Season   Weather  Tourist Labels  cost  extra
0  Summer  Pleasant     like    Yes   100     65
1  Summer       Hot  dislike    Yes   100     46
2  Summer  Pleasant     like    Yes   100      2
3  winter     Harsh     like    Yes   150     77
4  winter  Pleasant     like     No   150     55
5  autumn       Dry  dislike    Yes   200     97
6  autumn  Pleasant  dislike    Yes   200     39
7  autumn     Harsh      NaN     No   200     50
8  Spring  Pleasant     like    NaN   200      1

## to get help

In [12]:
?np.random.randint

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, 

In [114]:
DF

Season   Weather  Tourist Labels  cost  extra
0  Summer  Pleasant     like    Yes   100    125
1  Summer       Hot  dislike    Yes   100     62
2  Summer  Pleasant     like    Yes   100     90
3  winter     Harsh     like    Yes   150     50
4  winter  Pleasant     like     No   150     69
5  autumn       Dry  dislike    Yes   200     88
6  autumn  Pleasant  dislike    Yes   200    128
7  autumn     Harsh      NaN     No   200    107
8  Spring  Pleasant     like    NaN   200     69

# replacing specified values in a dataframe  using replace()

In [ ]:
DF.replace('Harsh', np.nan)

Season   Weather  Tourist  Labels  cost  extra
0  Summer  Pleasant     like    Rain   100     85
1  Summer       Hot  dislike    Rain   100     98
2  Summer  Pleasant     like    Rain   100     15
3  winter       NaN     like  Norain   200    123
4  winter  Pleasant     like  Norain   200    105
5  autumn       Dry  dislike  Norain   200     29
6  autumn  Pleasant  dislike  Norain   200      6
7  autumn       NaN      NaN  Norain   200     94
8  Spring  Pleasant     like    Rain   200     52

In [4]:
DF

Season   Weather  Tourist Labels
0  Summer  Pleasant     like    Yes
1  Summer       Hot  dislike    Yes
2  Summer  Pleasant     like    Yes
3  winter     Harsh     like    Yes
4  winter  Pleasant     like     No
5  autumn       Dry  dislike    Yes
6  autumn  Pleasant  dislike    Yes
7  autumn     Harsh      NaN     No
8  Spring  Pleasant     like    NaN

In [ ]:
DF.replace(['Harsh','Dry'], [np.nan,'Wet'])

Season   Weather  Tourist Labels  cost
0  Summer  Pleasant     like    Yes   100
1  Summer       Hot  dislike    Yes   100
2  Summer  Pleasant     like    Yes   100
3  winter       NaN     like    Yes   150
4  winter  Pleasant     like     No   150
5  autumn       Wet  dislike    Yes   200
6  autumn  Pleasant  dislike    Yes   200
7  autumn       NaN      NaN     No   200
8  Spring  Pleasant     like    NaN   200

## using dictionary, set replace values

In [ ]:
DF.replace({'Harsh': np.nan,'Dry':'Wet'})

Season   Weather  Tourist Labels  cost
0  Summer  Pleasant     like    Yes   100
1  Summer       Hot  dislike    Yes   100
2  Summer  Pleasant     like    Yes   100
3  winter       NaN     like    Yes   150
4  winter  Pleasant     like     No   150
5  autumn       Wet  dislike    Yes   200
6  autumn  Pleasant  dislike    Yes   200
7  autumn       NaN      NaN     No   200
8  Spring  Pleasant     like    NaN   200

## replacing value of a specific column

In [ ]:
DF['extra'].replace(range(70,100),100)

0    116
1    116
2    116
3    116
4    116
5    116
6    116
7    116
8    116
Name: extra, dtype: int64

In [ ]:
DF

Season   Weather  Tourist Labels  cost
0  Summer  Pleasant     like    Yes   100
1  Summer       Hot  dislike    Yes   100
2  Summer  Pleasant     like    Yes   100
3  winter     Harsh     like    Yes   150
4  winter  Pleasant     like     No   150
5  autumn       Dry  dislike    Yes   200
6  autumn  Pleasant  dislike    Yes   200
7  autumn     Harsh      NaN     No   200
8  Spring  Pleasant     like    NaN   200

# Manipulating data

## extracting selected values and manipulating but not changed in data

## write the problem statement for the following:

In [6]:
DF[DF['cost']>=150]*2


Season           Weather         Tourist  Labels  cost
3  winterwinter        HarshHarsh        likelike  YesYes   300
4  winterwinter  PleasantPleasant        likelike    NoNo   300
5  autumnautumn            DryDry  dislikedislike  YesYes   400
6  autumnautumn  PleasantPleasant  dislikedislike  YesYes   400
7  autumnautumn        HarshHarsh             NaN    NoNo   400
8  SpringSpring  PleasantPleasant        likelike     NaN   400

In [31]:
DF

Season   Weather  Tourist Labels  cost  extra
0  Summer  Pleasant     like    Yes   100    109
1  Summer       Hot  dislike    Yes   100     24
2  Summer  Pleasant     like    Yes   100     72
3  winter     Harsh     like    Yes   150    107
4  winter  Pleasant     like     No   150    108
5  autumn       Dry  dislike    Yes   200      5
6  autumn  Pleasant  dislike    Yes   200     93
7  autumn     Harsh      NaN     No   200     63
8  Spring  Pleasant     like    NaN   200     78

## problem: to double all values in extra which are > 70 and reflect changes in the column

In [8]:
fnlambda = lambda x: x*2 if x>=100 else x

In [9]:
DF['newcost']=DF['cost'].map(fnlambda)

In [10]:
DF

Season   Weather  Tourist Labels  cost  newcost
0  Summer  Pleasant     like    Yes   100      200
1  Summer       Hot  dislike    Yes   100      200
2  Summer  Pleasant     like    Yes   100      200
3  winter     Harsh     like    Yes   150      300
4  winter  Pleasant     like     No   150      300
5  autumn       Dry  dislike    Yes   200      400
6  autumn  Pleasant  dislike    Yes   200      400
7  autumn     Harsh      NaN     No   200      400
8  Spring  Pleasant     like    NaN   200      400

## Renaming Axis Indexes

In [11]:
transform = lambda x: "tourist"+str(x+1)
DF.index.map(transform)

Index(['tourist1', 'tourist2', 'tourist3', 'tourist4', 'tourist5', 'tourist6',
       'tourist7', 'tourist8', 'tourist9'],
      dtype='object')

In [12]:
DF.index=DF.index.map(transform)

## Change column labels to uppercase and Sort

In [159]:
DF.columns=DF.columns.str.upper()

In [13]:
DFnew=DF.sort_index(axis=1) 

In [14]:
DFnew

Labels  Season  Tourist   Weather  cost  newcost
tourist1    Yes  Summer     like  Pleasant   100      200
tourist2    Yes  Summer  dislike       Hot   100      200
tourist3    Yes  Summer     like  Pleasant   100      200
tourist4    Yes  winter     like     Harsh   150      300
tourist5     No  winter     like  Pleasant   150      300
tourist6    Yes  autumn  dislike       Dry   200      400
tourist7    Yes  autumn  dislike  Pleasant   200      400
tourist8     No  autumn      NaN     Harsh   200      400
tourist9    NaN  Spring     like  Pleasant   200      400

## using rename() and reflecting changes in original DF

In [16]:
DF=DF.rename(index={'TOURIST9': 'T9'},
            columns={'extra': 'expenditure'})

In [163]:
DF.rename(index={'TOURIST7': 'T7'},
            columns={'TOURIST': 'LIKENESS'},inplace=True)

In [17]:
DF

Season   Weather  Tourist Labels  cost  newcost  expenditure
tourist1  Summer  Pleasant     like    Yes   100      200          122
tourist2  Summer       Hot  dislike    Yes   100      200           24
tourist3  Summer  Pleasant     like    Yes   100      200           48
tourist4  winter     Harsh     like    Yes   150      300           45
tourist5  winter  Pleasant     like     No   150      300           41
tourist6  autumn       Dry  dislike    Yes   200      400           44
tourist7  autumn  Pleasant  dislike    Yes   200      400           91
tourist8  autumn     Harsh      NaN     No   200      400            3
tourist9  Spring  Pleasant     like    NaN   200      400           16

## making  a duplicate column name

In [20]:
DF=DF.rename(columns={'cost':'newcost'})

In [34]:
DF

Season   Weather  Tourist Labels newcost newcost expenditure
tourist1  Summer  Pleasant     like    Yes     100     200         122
tourist2  Summer       Hot  dislike    Yes     100     200          24
tourist3  Summer  Pleasant     like    Yes     100     200          48
tourist4  winter     Harsh     like    Yes     150     300          45
tourist5  winter  Pleasant     like     No     150     300          41
tourist6  autumn       Dry  dislike    Yes     200     400          44
tourist7  autumn  Pleasant  dislike    Yes     200     400          91
tourist8  autumn     Harsh      NaN     No     200     400           3
tourist9  Spring  Pleasant     like    NaN     200     400          16

In [24]:
DF['Newcol']=DF['expenditure']

In [29]:
DF=DF.T.drop_duplicates().T

In [31]:
DF.columns.get_loc('Tourist')

2

## get_loc() returns mask list for multiple columns with same name

In [32]:
mask=DF.columns.get_loc('newcost')

In [33]:
mask

array([False, False, False, False,  True,  True, False])

In [35]:
DF.columns.duplicated()

array([False, False, False, False, False,  True, False])

## removing last duplicate column

In [36]:
DF=DF.loc[:,~DF.columns.duplicated()]

In [38]:
DF

Season   Weather  Tourist Labels newcost expenditure
tourist1  Summer  Pleasant     like    Yes     100         122
tourist2  Summer       Hot  dislike    Yes     100          24
tourist3  Summer  Pleasant     like    Yes     100          48
tourist4  winter     Harsh     like    Yes     150          45
tourist5  winter  Pleasant     like     No     150          41
tourist6  autumn       Dry  dislike    Yes     200          44
tourist7  autumn  Pleasant  dislike    Yes     200          91
tourist8  autumn     Harsh      NaN     No     200           3
tourist9  Spring  Pleasant     like    NaN     200          16

In [115]:
DF

Season   Weather  Tourist Labels  cost  extra
0  Summer  Pleasant     like    Yes   100    125
1  Summer       Hot  dislike    Yes   100     62
2  Summer  Pleasant     like    Yes   100     90
3  winter     Harsh     like    Yes   150     50
4  winter  Pleasant     like     No   150     69
5  autumn       Dry  dislike    Yes   200     88
6  autumn  Pleasant  dislike    Yes   200    128
7  autumn     Harsh      NaN     No   200    107
8  Spring  Pleasant     like    NaN   200     69

In [66]:
DF.iloc[len(DF)-1]

SEASON        Spring
WEATHER     Pleasant
LIKENESS        like
LABELS           NaN
NEWCOST          200
EXTRA             78
NEWCOST          400
Name: tourist9, dtype: object

# explicitly adding a duplicate coulmn name if not in DF else removing the duplicate coulmn with same name

# user-defined fn to get duplicate colname position else returns len+1

In [41]:
def fnposcol():
  global DF
  A=DF.columns.duplicated()  #true/false value
  S=pd.Series(A)
  updated=len(DF)+100
  if S.nunique()!=1:
    for (i,x) in enumerate(A):
      if x==True:
       updated=i
       print("duplicate column at position:",updated)
  else:
    print("no duplicate column name")
    ans=input("do you want to add a duplicate column ? (Y/N)")
    if ans=='Y':
      DF['duplicatecol']=DF[DF.columns[len(DF.columns)-1]]
      print("adding a duplicate column")
      DF=DF.rename(columns={'duplicatecol':DF.columns[0]})
      display(DF)
      print("Duplicate column added ")
  return updated

In [39]:
DF

Season   Weather  Tourist Labels newcost expenditure
tourist1  Summer  Pleasant     like    Yes     100         122
tourist2  Summer       Hot  dislike    Yes     100          24
tourist3  Summer  Pleasant     like    Yes     100          48
tourist4  winter     Harsh     like    Yes     150          45
tourist5  winter  Pleasant     like     No     150          41
tourist6  autumn       Dry  dislike    Yes     200          44
tourist7  autumn  Pleasant  dislike    Yes     200          91
tourist8  autumn     Harsh      NaN     No     200           3
tourist9  Spring  Pleasant     like    NaN     200          16

In [135]:
DF.columns[0]

'Season'

In [173]:
print(DF.columns)

Index(['SEASON', 'WEATHER', 'LIKENESS', 'LABELS', 'NEWCOST', 'EXTRA'], dtype='object')


In [137]:
print(DF.columns.unique(), DF.columns.nunique())

Index(['Season', 'Weather', 'Tourist', 'Labels', 'cost', 'extra',
       'duplicatecol'],
      dtype='object') 7


In [42]:
pos=fnposcol()
if pos < len(DF.columns):
    print("duplicate column is already in DF at position: ",pos)
else:
    print("duplicate column name added")

no duplicate column name
adding a duplicate column


Season   Weather  Tourist Labels newcost expenditure Season
tourist1  Summer  Pleasant     like    Yes     100         122    122
tourist2  Summer       Hot  dislike    Yes     100          24     24
tourist3  Summer  Pleasant     like    Yes     100          48     48
tourist4  winter     Harsh     like    Yes     150          45     45
tourist5  winter  Pleasant     like     No     150          41     41
tourist6  autumn       Dry  dislike    Yes     200          44     44
tourist7  autumn  Pleasant  dislike    Yes     200          91     91
tourist8  autumn     Harsh      NaN     No     200           3      3
tourist9  Spring  Pleasant     like    NaN     200          16     16

Duplicate column added 
duplicate column name added


## to add a new column

In [43]:
DF.insert(0,'Extra',value=100,allow_duplicates=True)

## first method to remove duplicate column, Make sure all names are in same cases

In [221]:
DF.columns

Index(['Extra', 'EXTRA', 'Extra', 'Labels', 'Likeness', 'Newcost', 'Season',
       'Weather', 'Cost', 'Cost'],
      dtype='object')

In [45]:

DF.columns=DF.columns.str.capitalize()
DF.sort_index(axis=1,inplace=True)

In [49]:
DF

Expenditure  Extra Labels Newcost  Season Season  Tourist   Weather
tourist1         122    100    Yes     100  Summer    122     like  Pleasant
tourist2          24    100    Yes     100  Summer     24  dislike       Hot
tourist3          48    100    Yes     100  Summer     48     like  Pleasant
tourist4          45    100    Yes     150  winter     45     like     Harsh
tourist5          41    100     No     150  winter     41     like  Pleasant
tourist6          44    100    Yes     200  autumn     44  dislike       Dry
tourist7          91    100    Yes     200  autumn     91  dislike  Pleasant
tourist8           3    100     No     200  autumn      3      NaN     Harsh
tourist9          16    100    NaN     200  Spring     16     like  Pleasant

## Display values in duplicate columns only

In [48]:
print(DF.columns.get_loc(key='Season'))  #returns boolean mask if index/columns are not arranged
L=DF.columns.get_loc(key='Season')
DF.iloc[:,L]

slice(4, 6, None)


Season Season
tourist1  Summer    122
tourist2  Summer     24
tourist3  Summer     48
tourist4  winter     45
tourist5  winter     41
tourist6  autumn     44
tourist7  autumn     91
tourist8  autumn      3
tourist9  Spring     16

In [196]:
pos

5

In [194]:
columnsretained = [e for e in range(DF.shape[1]) if e not in [pos]]
columnsretained 
DF1=DF.iloc[:,columnsretained]

In [195]:
DF1

Extra Labels Likeness  Newcost  Season   Weather
tourist1      6    Yes     like      100  Summer  Pleasant
tourist2     65    Yes  dislike      100  Summer       Hot
tourist3     86    Yes     like      100  Summer  Pleasant
tourist4     84    Yes     like      150  winter     Harsh
tourist5     39     No     like      150  winter  Pleasant
tourist6     48    Yes  dislike      200  autumn       Dry
tourist7     85    Yes  dislike      200  autumn  Pleasant
tourist8    108     No      NaN      200  autumn     Harsh
tourist9    102    NaN     like      200  Spring  Pleasant

## dropping both duplicate coulmns

In [51]:
pos=4

In [52]:
DF1= DF.drop(DF.columns[[pos]],axis = 1)
DF1

Expenditure  Extra Labels Newcost  Tourist   Weather
tourist1         122    100    Yes     100     like  Pleasant
tourist2          24    100    Yes     100  dislike       Hot
tourist3          48    100    Yes     100     like  Pleasant
tourist4          45    100    Yes     150     like     Harsh
tourist5          41    100     No     150     like  Pleasant
tourist6          44    100    Yes     200  dislike       Dry
tourist7          91    100    Yes     200  dislike  Pleasant
tourist8           3    100     No     200      NaN     Harsh
tourist9          16    100    NaN     200     like  Pleasant

## Drop duplicate columns where column index may be different but values are same

In [199]:
DF['NewCol']=DF['Weather']

In [200]:
DF

Extra Labels Likeness  Newcost  Season  Season   Weather    NewCol
tourist1      6    Yes     like      100  Summer       6  Pleasant  Pleasant
tourist2     65    Yes  dislike      100  Summer      65       Hot       Hot
tourist3     86    Yes     like      100  Summer      86  Pleasant  Pleasant
tourist4     84    Yes     like      150  winter      84     Harsh     Harsh
tourist5     39     No     like      150  winter      39  Pleasant  Pleasant
tourist6     48    Yes  dislike      200  autumn      48       Dry       Dry
tourist7     85    Yes  dislike      200  autumn      85  Pleasant  Pleasant
tourist8    108     No      NaN      200  autumn     108     Harsh     Harsh
tourist9    102    NaN     like      200  Spring     102  Pleasant  Pleasant

In [202]:
DF=DF.T.drop_duplicates(keep='first').T

In [204]:
DF

Extra Labels Likeness Newcost  Season   Weather
tourist1     6    Yes     like     100  Summer  Pleasant
tourist2    65    Yes  dislike     100  Summer       Hot
tourist3    86    Yes     like     100  Summer  Pleasant
tourist4    84    Yes     like     150  winter     Harsh
tourist5    39     No     like     150  winter  Pleasant
tourist6    48    Yes  dislike     200  autumn       Dry
tourist7    85    Yes  dislike     200  autumn  Pleasant
tourist8   108     No      NaN     200  autumn     Harsh
tourist9   102    NaN     like     200  Spring  Pleasant

## Second method to remove duplicate col names

In [225]:
~DF.columns.duplicated()

array([ True, False,  True, False, False,  True,  True,  True,  True,
        True])

In [226]:
DF.loc[:,~DF.columns.duplicated()]

Cost  Extra Labels Likeness Newcost  Season  \
tourist1  Pleasant    100    Yes     like     100  Summer   
tourist2       Hot    100    Yes  dislike     100  Summer   
tourist3  Pleasant    100    Yes     like     100  Summer   
tourist4     Harsh    100    Yes     like     150  winter   
tourist5  Pleasant    100     No     like     150  winter   
tourist6       Dry    100    Yes  dislike     200  autumn   
tourist7  Pleasant    100    Yes  dislike     200  autumn   
tourist8     Harsh    100     No      NaN     200  autumn   
tourist9  Pleasant    100    NaN     like     200  Spring   

                                           Weather  
tourist1  PleasantPleasantPleasantPleasantPleasant  
tourist2                           HotHotHotHotHot  
tourist3  PleasantPleasantPleasantPleasantPleasant  
tourist4                 HarshHarshHarshHarshHarsh  
tourist5  PleasantPleasantPleasantPleasantPleasant  
tourist6                           DryDryDryDryDry  
tourist7  PleasantPleasantPleasantPleasantPleasant  
tourist8                 HarshHarshHarshHarshHarsh  
tourist9  PleasantPleasantPleasantPleasantPleasant

## Code to add a duplicate column name in case DF does not have. If duplicate column name then delete last duplicate  column

In [212]:
A=DF.columns.duplicated()  #true/false value
S=pd.Series(A)
if S.nunique()==1:
  DF['duplicatecol']=DF[DF.columns[len(DF.columns)-1]]
  print("adding a duplicate column")
  DF=DF.rename(columns={'duplicatecol':'Cost'})  #making duplicate column
else:
  print("duplicate column name and removing it")
  DF.columns.duplicated()
  DF.loc[:,DF.columns.duplicated()] #rerieve duplicate column value
  DF=DF.loc[:,~DF.columns.duplicated()] #rerieve non-duplicate column names with data
  

adding a duplicate column


In [210]:
DF

Extra Labels Likeness Newcost  Season   Weather      Cost
tourist1     6    Yes     like     100  Summer  Pleasant  Pleasant
tourist2    65    Yes  dislike     100  Summer       Hot       Hot
tourist3    86    Yes     like     100  Summer  Pleasant  Pleasant
tourist4    84    Yes     like     150  winter     Harsh     Harsh
tourist5    39     No     like     150  winter  Pleasant  Pleasant
tourist6    48    Yes  dislike     200  autumn       Dry       Dry
tourist7    85    Yes  dislike     200  autumn  Pleasant  Pleasant
tourist8   108     No      NaN     200  autumn     Harsh     Harsh
tourist9   102    NaN     like     200  Spring  Pleasant  Pleasant

## to change value in duplicated column

In [216]:
DF.iloc[:,pos]*=5

In [217]:
DF

Extra Labels Likeness Newcost  Season  \
tourist1     6    Yes     like     100  Summer   
tourist2    65    Yes  dislike     100  Summer   
tourist3    86    Yes     like     100  Summer   
tourist4    84    Yes     like     150  winter   
tourist5    39     No     like     150  winter   
tourist6    48    Yes  dislike     200  autumn   
tourist7    85    Yes  dislike     200  autumn   
tourist8   108     No      NaN     200  autumn   
tourist9   102    NaN     like     200  Spring   

                                           Weather      Cost      Cost  
tourist1  PleasantPleasantPleasantPleasantPleasant  Pleasant  Pleasant  
tourist2                           HotHotHotHotHot       Hot       Hot  
tourist3  PleasantPleasantPleasantPleasantPleasant  Pleasant  Pleasant  
tourist4                 HarshHarshHarshHarshHarsh     Harsh     Harsh  
tourist5  PleasantPleasantPleasantPleasantPleasant  Pleasant  Pleasant  
tourist6                           DryDryDryDryDry       Dry       Dry  
tourist7  PleasantPleasantPleasantPleasantPleasant  Pleasant  Pleasant  
tourist8                 HarshHarshHarshHarshHarsh     Harsh     Harsh  
tourist9  PleasantPleasantPleasantPleasantPleasant  Pleasant  Pleasant

In [ ]:
type(DF.columns)

pandas.core.indexes.base.Index

## to check if two columns are having exactly same values

In [227]:
DF

Cost      Cost Extra Extra Extra Labels Likeness Newcost  \
tourist1  Pleasant  Pleasant   100   100     6    Yes     like     100   
tourist2       Hot       Hot   100   100    65    Yes  dislike     100   
tourist3  Pleasant  Pleasant   100   100    86    Yes     like     100   
tourist4     Harsh     Harsh   100   100    84    Yes     like     150   
tourist5  Pleasant  Pleasant   100   100    39     No     like     150   
tourist6       Dry       Dry   100   100    48    Yes  dislike     200   
tourist7  Pleasant  Pleasant   100   100    85    Yes  dislike     200   
tourist8     Harsh     Harsh   100   100   108     No      NaN     200   
tourist9  Pleasant  Pleasant   100   100   102    NaN     like     200   

          Season                                   Weather  
tourist1  Summer  PleasantPleasantPleasantPleasantPleasant  
tourist2  Summer                           HotHotHotHotHot  
tourist3  Summer  PleasantPleasantPleasantPleasantPleasant  
tourist4  winter                 HarshHarshHarshHarshHarsh  
tourist5  winter  PleasantPleasantPleasantPleasantPleasant  
tourist6  autumn                           DryDryDryDryDry  
tourist7  autumn  PleasantPleasantPleasantPleasantPleasant  
tourist8  autumn                 HarshHarshHarshHarshHarsh  
tourist9  Spring  PleasantPleasantPleasantPleasantPleasant

In [70]:
DF['newcol']=DF['cost']

In [72]:
DF.iloc[:,5]

0    100
1    100
2    100
3    150
4    150
5    200
6    200
7    200
8    200
Name: newcol, dtype: int64

In [233]:
DF.columns

Index(['Cost', 'Cost', 'Extra', 'Extra', 'Extra', 'Labels', 'Likeness',
       'Newcost', 'Season', 'Weather'],
      dtype='object')

In [241]:
DF[DF.columns[3]]

Extra Extra Extra
tourist1   100   100     6
tourist2   100   100    65
tourist3   100   100    86
tourist4   100   100    84
tourist5   100   100    39
tourist6   100   100    48
tourist7   100   100    85
tourist8   100   100   108
tourist9   100   100   102

In [240]:
DF.columns[3]

'Extra'

In [242]:
DF[DF.columns[3]].iloc[:,2]

tourist1      6
tourist2     65
tourist3     86
tourist4     84
tourist5     39
tourist6     48
tourist7     85
tourist8    108
tourist9    102
Name: Extra, dtype: object

In [245]:
(DF[DF.columns[3]].iloc[:,1]==DF[DF.columns[3]].iloc[:,2]).unique()

array([False])

In [53]:
DF[DF.columns[6]].equals(DF[DF.columns[7]])

False

In [59]:
DF

Expenditure  Cost Labels Newcost  Season Season  Tourist   Weather
tourist1         122   100    Yes     100  Summer    122     like  Pleasant
tourist2          24   100    Yes     100  Summer     24  dislike       Hot
tourist3          48   100    Yes     100  Summer     48     like  Pleasant
tourist4          45   100    Yes     150  winter     45     like     Harsh
tourist5          41   100     No     150  winter     41     like  Pleasant
tourist6          44   100    Yes     200  autumn     44  dislike       Dry
tourist7          91   100    Yes     200  autumn     91  dislike  Pleasant
tourist8           3   100     No     200  autumn      3      NaN     Harsh
tourist9          16   100    NaN     200  Spring     16     like  Pleasant

In [58]:
DF=DF.rename({'Extra':'Cost'},axis=1)

# discreization of numeric data into bins


1.   Explicitly mentioning of bin range
2.   number of bins of same size (bin range)







In [62]:
DF['Newcost1']=DF['Cost']+DF['Newcost']

In [63]:
DF.sort_values(by='Newcost1')

Expenditure  Cost Labels Newcost  Season Season  Tourist   Weather  \
tourist1         122   100    Yes     100  Summer    122     like  Pleasant   
tourist2          24   100    Yes     100  Summer     24  dislike       Hot   
tourist3          48   100    Yes     100  Summer     48     like  Pleasant   
tourist4          45   100    Yes     150  winter     45     like     Harsh   
tourist5          41   100     No     150  winter     41     like  Pleasant   
tourist6          44   100    Yes     200  autumn     44  dislike       Dry   
tourist7          91   100    Yes     200  autumn     91  dislike  Pleasant   
tourist8           3   100     No     200  autumn      3      NaN     Harsh   
tourist9          16   100    NaN     200  Spring     16     like  Pleasant   

         Newcost1  
tourist1      200  
tourist2      200  
tourist3      200  
tourist4      250  
tourist5      250  
tourist6      300  
tourist7      300  
tourist8      300  
tourist9      300

In [ ]:
DF.columns.str.lower()

Index(['season', 'weather', 'likeness', 'labels', 'cost', 'extra', 'newcost',
       'newcost'],
      dtype='object')

In [255]:
DF.columns=DF.columns.str.lower()

In [65]:
DF

Expenditure  Cost Labels Newcost  Season Season  Tourist   Weather  \
tourist1         122   100    Yes     100  Summer    122     like  Pleasant   
tourist2          24   100    Yes     100  Summer     24  dislike       Hot   
tourist3          48   100    Yes     100  Summer     48     like  Pleasant   
tourist4          45   100    Yes     150  winter     45     like     Harsh   
tourist5          41   100     No     150  winter     41     like  Pleasant   
tourist6          44   100    Yes     200  autumn     44  dislike       Dry   
tourist7          91   100    Yes     200  autumn     91  dislike  Pleasant   
tourist8           3   100     No     200  autumn      3      NaN     Harsh   
tourist9          16   100    NaN     200  Spring     16     like  Pleasant   

         Newcost1  
tourist1      200  
tourist2      200  
tourist3      200  
tourist4      250  
tourist5      250  
tourist6      300  
tourist7      300  
tourist8      300  
tourist9      300

 ## bin method-1

In [64]:
DF

Expenditure  Cost Labels Newcost  Season Season  Tourist   Weather  \
tourist1         122   100    Yes     100  Summer    122     like  Pleasant   
tourist2          24   100    Yes     100  Summer     24  dislike       Hot   
tourist3          48   100    Yes     100  Summer     48     like  Pleasant   
tourist4          45   100    Yes     150  winter     45     like     Harsh   
tourist5          41   100     No     150  winter     41     like  Pleasant   
tourist6          44   100    Yes     200  autumn     44  dislike       Dry   
tourist7          91   100    Yes     200  autumn     91  dislike  Pleasant   
tourist8           3   100     No     200  autumn      3      NaN     Harsh   
tourist9          16   100    NaN     200  Spring     16     like  Pleasant   

         Newcost1  
tourist1      200  
tourist2      200  
tourist3      200  
tourist4      250  
tourist5      250  
tourist6      300  
tourist7      300  
tourist8      300  
tourist9      300

In [67]:
bins = [0,40, 75,97, 150]
category = pd.cut(DF['Expenditure'], bins)
category

tourist1    (97, 150]
tourist2      (0, 40]
tourist3     (40, 75]
tourist4     (40, 75]
tourist5     (40, 75]
tourist6     (40, 75]
tourist7     (75, 97]
tourist8      (0, 40]
tourist9      (0, 40]
Name: Expenditure, dtype: category
Categories (4, interval[int64]): [(0, 40] < (40, 75] < (75, 97] < (97, 150]]

## constructing user specified bins in range min-max of that column

In [68]:
m=DF['Expenditure'].min()
max1=DF['Expenditure'].max()

In [73]:
A=np.arange(m-1,max1+1,20)
A

array([  2,  22,  42,  62,  82, 102, 122])

In [269]:
A[4]

81

In [70]:
B=np.append(A,max1)

In [74]:
category = pd.cut(DF['Expenditure'], A)

In [75]:
category

tourist1    (102, 122]
tourist2      (22, 42]
tourist3      (42, 62]
tourist4      (42, 62]
tourist5      (22, 42]
tourist6      (42, 62]
tourist7     (82, 102]
tourist8       (2, 22]
tourist9       (2, 22]
Name: Expenditure, dtype: category
Categories (6, interval[int64]): [(2, 22] < (22, 42] < (42, 62] < (62, 82] < (82, 102] < (102, 122]]

## to get the bin range

In [103]:
DF['extra']

0    550
1    644
2    450
3    834
4    818
5    508
6    669
7    374
8    569
Name: extra, dtype: int64

In [76]:
category.values

[(102, 122], (22, 42], (42, 62], (42, 62], (22, 42], (42, 62], (82, 102], (2, 22], (2, 22]]
Categories (6, interval[int64]): [(2, 22] < (22, 42] < (42, 62] < (62, 82] < (82, 102] < (102, 122]]

## Extract bin code

In [77]:
category.values.codes

array([5, 1, 2, 2, 1, 2, 4, 0, 0], dtype=int8)

## extract all bin categories

In [78]:
category.values.categories

IntervalIndex([(2, 22], (22, 42], (42, 62], (62, 82], (82, 102], (102, 122]],
              closed='right',
              dtype='interval[int64]')

## as per math notation []: closed parenthesis, () :open
By defualt, right parenthesis is closed in cut().
May be mentioned (right=False) in pd.cut()

In [82]:
category=pd.cut(DF['Expenditure'], bins, right=False)

In [83]:
L=len(category.values.categories)
L

4

## labels size must be same as that of categories size

In [84]:
categories_names = ['low', 'moderate', 'costly','much cost']
pd.cut(DF['Expenditure'], bins, right=False,labels=categories_names[0:L])

tourist1    much cost
tourist2          low
tourist3     moderate
tourist4     moderate
tourist5     moderate
tourist6     moderate
tourist7       costly
tourist8          low
tourist9          low
Name: Expenditure, dtype: category
Categories (4, object): ['low' < 'moderate' < 'costly' < 'much cost']

# Bin method 2: equal sized bin

In [85]:
data = np.random.rand(30)
pd.cut(data, 5, precision=2)

[(0.78, 0.96], (0.78, 0.96], (0.78, 0.96], (0.22, 0.41], (0.41, 0.59], ..., (0.035, 0.22], (0.41, 0.59], (0.59, 0.78], (0.035, 0.22], (0.78, 0.96]]
Length: 30
Categories (5, interval[float64]): [(0.035, 0.22] < (0.22, 0.41] < (0.41, 0.59] < (0.59, 0.78] < (0.78, 0.96]]

In [86]:
data

array([0.87144828, 0.94383328, 0.91169031, 0.34393941, 0.44467372,
       0.96428163, 0.21876247, 0.25433755, 0.75069521, 0.65393665,
       0.8988803 , 0.03613184, 0.14283265, 0.1889172 , 0.23203964,
       0.33260684, 0.72345063, 0.08440049, 0.73885632, 0.53341119,
       0.67301264, 0.29183708, 0.36450946, 0.18263377, 0.72620641,
       0.08684753, 0.49576954, 0.75034658, 0.06934315, 0.86514492])

# Bin method 3: mentioning number of items in each bin as per quartile

In [3]:
data = np.random.randn(1000)  # Normally distributed
cats = pd.qcut(data, 4)  # Cut into quartiles (25%,50%,75%,100%)
cats


[(-0.667, 0.00255], (-3.5029999999999997, -0.667], (-0.667, 0.00255], (-0.667, 0.00255], (0.577, 3.59], ..., (-3.5029999999999997, -0.667], (-0.667, 0.00255], (-3.5029999999999997, -0.667], (-3.5029999999999997, -0.667], (0.00255, 0.577]]
Length: 1000
Categories (4, interval[float64]): [(-3.5029999999999997, -0.667] < (-0.667, 0.00255] < (0.00255, 0.577] < (0.577, 3.59]]

In [4]:
cats.codes[:20]

array([3, 1, 1, 3, 0, 0, 3, 3, 1, 1, 1, 0, 3, 0, 1, 1, 2, 1, 0, 1],
      dtype=int8)

In [4]:
pd.value_counts(cats)

(-3.5029999999999997, -0.667]    250
(-0.667, 0.00255]                250
(0.00255, 0.577]                 250
(0.577, 3.59]                    250
dtype: int64

## explicitly mentioning the quantiles: % of items in a bin

In [5]:
cats=pd.qcut(data, [0, 0.15, 0.3, 0.8, 1.])

In [6]:
pd.value_counts(cats)

(-0.522, 0.783]                  500
(0.783, 3.59]                    200
(-3.5029999999999997, -0.979]    150
(-0.979, -0.522]                 150
dtype: int64

# detecting outliers: extreme values which may impact the rest of data, may be encountered due to typos/malfunctioing of data capturing devices etc.

In [7]:
DF=pd.DataFrame(np.random.randn(100,5))

In [8]:
DF

0         1         2         3         4
0   1.682788 -1.195067 -0.740066  1.160429 -0.498522
1   0.578504 -0.149330  1.377304  0.622857  0.813290
2  -0.572642  1.551633  0.798107 -0.926004 -0.908249
3  -0.379036 -1.562295  1.259371 -0.718929 -0.604311
4   0.514396 -0.650772  0.335942  1.311719  1.558992
..       ...       ...       ...       ...       ...
95 -0.302700 -0.236066 -0.523154 -0.111150  1.882567
96 -0.188035 -1.533557  0.217998  0.468380  1.253355
97  0.340923  1.483356  0.436851 -0.077904 -0.431021
98  1.571096  0.482937 -1.157455 -2.133452  1.199743
99 -0.192576  1.687127 -1.262977 -0.304180  1.395418

[100 rows x 5 columns]

## tatistical description of data

In [9]:
DF.describe()

0           1           2           3           4
count  100.000000  100.000000  100.000000  100.000000  100.000000
mean     0.173761   -0.010555   -0.159829   -0.144575    0.195420
std      0.869844    0.997745    1.160864    1.050878    1.044626
min     -1.670473   -2.123522   -3.232502   -2.701941   -2.671150
25%     -0.381689   -0.716150   -0.995745   -0.875636   -0.523246
50%      0.192041    0.002510   -0.117642   -0.162282    0.144960
75%      0.740922    0.741080    0.496672    0.672364    0.832484
max      2.286897    2.490731    3.057173    1.809799    2.283933

In [10]:
mean_val=DF[1].mean()

In [11]:
mean_val

-0.010554627828832217

In [12]:
std_val=DF[1].std()

In [14]:
std_val

0.9977448215911002

In [15]:
mean_val+2*std_val

1.9849350153533682

In [16]:
DF[DF[1]> (mean_val+2*std_val)]

0         1         2         3         4
39 -1.107721  2.490731  3.057173  0.776042  0.911639

In [20]:
cats=pd.cut(DF[1], [DF[1].min(),-1.5,-0.2,1,1.98,DF[1].max()],precision=6)

In [21]:
cats

0          (-1.5, -0.2]
1           (-0.2, 1.0]
2           (1.0, 1.98]
3     (-2.123522, -1.5]
4          (-1.5, -0.2]
            ...        
95         (-1.5, -0.2]
96    (-2.123522, -1.5]
97          (1.0, 1.98]
98          (-0.2, 1.0]
99          (1.0, 1.98]
Name: 1, Length: 100, dtype: category
Categories (5, interval[float64]): [(-2.123522, -1.5] < (-1.5, -0.2] < (-0.2, 1.0] < (1.0, 1.98] < (1.98, 2.490731]]

In [22]:
pd.value_counts(cats)

(-0.2, 1.0]          43
(-1.5, -0.2]         33
(1.0, 1.98]          15
(-2.123522, -1.5]     7
(1.98, 2.490731]      1
Name: 1, dtype: int64

In [23]:
cats.values.codes

array([ 1,  2,  3,  0,  1,  1,  2,  1,  2,  1,  2,  1, -1,  1,  1,  2,  1,
        3,  2,  3,  2,  2,  2,  2,  1,  1,  2,  2,  1,  3,  2,  2,  0,  1,
        1,  2,  1,  0,  2,  4,  3,  2,  3,  2,  2,  0,  1,  2,  1,  2,  2,
        2,  3,  2,  2,  1,  2,  2,  2,  2,  2,  1,  1,  1,  2,  1,  3,  2,
        1,  2,  1,  1,  3,  2,  1,  3,  2,  0,  3,  2,  1,  2,  1,  2,  1,
        1,  0,  2,  3,  1,  2,  1,  2,  2,  3,  1,  0,  3,  2,  3],
      dtype=int8)

In [24]:
sum(cats.values.isna())

1

In [25]:
DF[DF[1]>DF[1].max()-0.5]

0         1         2         3         4
39 -1.107721  2.490731  3.057173  0.776042  0.911639

In [26]:
DF[DF[1]<DF[1].min()+0.5]

0         1         2         3         4
12 -0.207127 -2.123522 -0.759591 -0.653296 -0.631563
45 -0.233660 -2.084028 -0.900581 -0.535659  0.286339
77  1.463852 -1.677775  2.216755 -0.363827  0.593722
86 -0.296649 -1.802060  0.299284  1.603780 -0.295481

## get sign value of data

In [27]:
np.sign(DF[1])

0    -1.0
1    -1.0
2     1.0
3    -1.0
4    -1.0
     ... 
95   -1.0
96   -1.0
97    1.0
98    1.0
99    1.0
Name: 1, Length: 100, dtype: float64

In [161]:
DF[1].median()

0.03312212078834947

## setting extreme values to median of a colume

In [33]:
DF[DF[1]>(mean_val+2*std_val)]

0         1         2         3         4
2   1.277768  1.747110  0.057100  0.110485  0.575087
6  -0.878947  1.990347  1.180281 -1.007779  0.147126
65  0.773281  2.291504  1.289712  1.357138 -0.840155

In [34]:
DF.loc[DF[1]>(mean_val+2*std_val)]=DF[1].median()

In [35]:
DF.iloc[63,:]

0   -2.190247
1    0.444477
2    0.031868
3   -1.115743
4   -1.535025
Name: 63, dtype: float64

# string object operations

1.   count: the number of non-overlapping occurrences of substring in the string.

2.   endswith: returns True if string ends with mentioned suffix.

1.    startswith: returns True if string starts with mentioned prefix.
2.   index: returns position of first character in substring if found in the string; raises ValueError if not found.


1.   find: returns position of first character in substring if found in the string; else -1
2.   strip: Trim whitespace, including newlines (and rstrip, lstrip, respectively)


1.   split: to split a string into substring based on mentioned delimiters
2.   join: joining substrings in a string using mentioned delilimters
ljust(),lower(),










In [29]:
msg=' It is   gooD to know, All the Classmates are good '

## casefold same as lower() but with only difference in handling of language/region-specific character 

In [30]:
msg.casefold()

' it is   good to know, all the classmates are good '

In [31]:
msg.lower()

' it is   good to know, all the classmates are good '

## split(): splits on the basis of single seperatoe. If mulitple seperators then use regular expression (re)

In [43]:
msg.split(sep=',')

[' It is   gooD to know', ' All the Classmates are good ']

In [44]:
msg.count('good')

1

In [45]:
msg.replace(',','**')

' It is   gooD to know** All the Classmates are good '

In [ ]:
len(msg)

51

In [32]:
msg.rjust(55,'*')

'**** It is   gooD to know, All the Classmates are good '

## Creating dummy variables for modeling
We often transform categorical data into dummy variables, also known as one-hot encoding while performing statistical analysis or machine learning. This involves creating
a DataFrame with a column for each distinct category; these columns contain 1s
for occurrences of a given category and 0 otherwise. number of columns created are equal to number of distinct categories

In [90]:
S1 = pd.Series(['a', 'b', 'c', 'd'] * 2)  # or you mau use explicit , dtype='category' while creating series

In [92]:
S1

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: object

In [91]:
dummy_var=pd.get_dummies(S1)
dummy_var

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1