# **Assignment 1**

| **Name** |Pratham Sharma|
|-------- | ------ |
|**Roll No** | AC-1232 |
| **Batch** | 2023 |
| **Submitted to** | Prof. Sharanjit Kaur|


## **Question - 1**

Given below is a dictionary having two keys ‘Boys’ and ‘Girls’ and having two lists of heights of five Boys and Five Girls respectively as values associated with these keysOriginal dictionary of lists :

{'Boys': [72, 68, 70, 69, 74], 'Girls': [63, 65, 69, 62, 61]}

From the given dictionary of lists create the following list of dictionaries : 

[{'Boys': 72, 'Girls': 63}, {'Boys': 68, 'Girls': 65}, {'Boys': 70, 'Girls': 69}, {'Boys': 69, 'Girls': 62}, {‘Boys’:74,‘Girls’:61]

In [143]:
heights = {'Boys': [72, 68, 70, 69, 74], 'Girls': [63, 65, 69, 62, 61]}
[{'Boys':x,'Girls':y} for x, y in zip(heights['Boys'], heights['Girls'])] # converting a dictionary of lists to list of dictionaries

[{'Boys': 72, 'Girls': 63},
 {'Boys': 68, 'Girls': 65},
 {'Boys': 70, 'Girls': 69},
 {'Boys': 69, 'Girls': 62},
 {'Boys': 74, 'Girls': 61}]

## **Question - 2**
Given are three lists where L1 has names of n students, L2 has marks and L3 has hobbies of n students.
Using three lists, create the following dictionary with hobbies as keys and (names,marks) as values.
In case more than one student has same hobby then values must be appended for the same key instead of overwriting. E.g.

L1 = ['A','B','C'], L2=[100,40,50], L3=['painting','music','painting']
then output should be : 

dict1 = {painting:(('A',100),('C',50)), 'music': ('B',40)}

In [2]:
L1 = ['A','B','C'] 
L2 = [100,40,50]
L3 = ['painting','music','painting']

{m3: tuple((l1,l2) for l1,l2,l3 in zip(L1,L2,L3) if l3==m3) for m3 in L3} # dictionary with L3 as key and L1,L2 as values

{'painting': (('A', 100), ('C', 50)), 'music': (('B', 40),)}


## **Question - 3**

Write  two  lambda functions 

1. One to  arrange a list of names on the last letter of the name i.e names = ['axc','bxbb','xxb','zzxy','zzc'] then new sorted list on last letter  is ['bxbb', 'xxb', 'axc', 'zzc', 'zzxy']
2. Second lambda function arranges list on the length of names and store results in dictionary with length as key and value as names

In [38]:
names1 = ['axc','bxbb','xxb','zzxy','zzc']
sorted(names1, key=lambda x: x[-1]) # sorting the list on the basis of last element

['bxbb', 'xxb', 'axc', 'zzc', 'zzxy']

In [202]:
names2 = ['axc','bxbb','xxb','azzxdy','zc']
{x:len(x) for x in sorted(names2, key=lambda x:len(x))} # arranging list in dictionary with sorted elements & their length as key-value pair

{'zc': 2, 'axc': 3, 'xxb': 3, 'bxbb': 4, 'azzxdy': 6}

## **Question - 4**

Write programs in Python using NumPy library to do the following : 

1. Compute the mean, standard deviation, and variance of a two dimensional random integer array along the second axis.
2. Get the indices of the sorted elements of a given array.B= [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
3. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and datatype of the array and then reshape it into nx m array, n and m are user inputs given at the run time.
4. Test whether the elements of a given array are zero, non-zero and NaN. Record the indices ofthese elements in three separate arrays.

In [3]:
import numpy as np

In [208]:
A = np.random.randint(1,9,size=(4,4)) # generating random integrer array of size 4x4
print(
	'Array => \n', A, '\n\n' # printing array
	'1. Mean => ', np.mean(A, axis=1), '\n' # printing mean of array along the second axis
	'2. Standard Deviation => ', np.std(A, axis=1), '\n' # printing Standard Deviation of array along second axis
	'3. Variance => ', np.var(A, axis=1) # printing variance of array along second axis
)

Array => 
 [[7 1 7 3]
 [3 6 3 8]
 [7 7 4 5]
 [8 6 2 5]] 

1. Mean =>  [4.5  5.   5.75 5.25] 
2. Standard Deviation =>  [2.59807621 2.12132034 1.29903811 2.16506351] 
3. Variance =>  [6.75   4.5    1.6875 4.6875]


In [33]:
B = np.array([56, 48, 22, 41, 78, 91, 24, 46, 8, 33])
print(np.argsort(B, axis=-1)) # printing indices of sorted elements of array

[8 2 6 9 3 7 1 0 4 5]


In [28]:
m = int(input('Enter the value of m => ')) 
n = int(input('Enter the value of n => '))
C = np.random.randint(1,9, size=(m,n)) # generating a random array with size mxn

print(
	'Array => \n', C, '\n\n' # print array
	'1. Shape of Array =>', C.shape, '\n' # print shape of array
	'2. Type of Array =>', type(C), '\n' # print type of array
	'3. Datatype of Array =>', type(C.data), '\n' # print datatype of array
	'4. Reshaped Array =>\n', C.reshape(n,m) # reshape array with new shape (n,m)
)

Array => 
 [[8 6 1 5]
 [5 6 8 7]
 [2 3 8 1]] 

1. Shape of Array => (3, 4) 
2. Type of Array => <class 'numpy.ndarray'> 
3. Datatype of Array => <class 'memoryview'> 
4. Reshaped Array =>
 [[8 6 1]
 [5 5 6]
 [8 7 2]
 [3 8 1]]


In [136]:
D = np.array([0, 2, 0, None, 3, 0, 42, 1, None, 3, 4, 0]) # sample array with 0, non-zero and NaN values 
print(
	'Array => ',D,'\n' #print array
	'No of Zeroes =>', np.where(D==0)[0],'\n' # print indices where elements are 0
	'No of Non Zeroes =>', np.where((D!=0) & (D!=None))[0],'\n' # print indices where elements are not 0
	'No of None => ', np.where(D==None)[0] # print indices where elements are NaN
)


Array =>  [0 2 0 None 3 0 42 1 None 3 4 0] 
No of Zeroes => [ 0  2  5 11] 
No of Non Zeroes => [ 1  4  6  7  9 10] 
No of None =>  [3 8]


## **Question - 5**

Generate a 2D array having values from 1 to 100  of shape (4,5).

1. Multiply all elements that are greater than 50 by 2
2. Extract 2x2  lower-right matrix from the given array and find its largest element   

In [4]:
E = np.random.randint(1,100,(4,5)) #generating random numpy array of shape (4,5) & range(1,100)
E

array([[43, 25, 68, 90, 52],
       [84, 22, 36, 53, 63],
       [55, 90,  9, 91,  6],
       [31, 62, 28, 77, 41]])

In [5]:
E[E>50] *= 2 # multiplying elements greater than 50 by 2
E #output

array([[ 43,  25, 136, 180, 104],
       [168,  22,  36, 106, 126],
       [110, 180,   9, 182,   6],
       [ 31, 124,  28, 154,  41]])

In [18]:
E[-2:,-2:].max()

182